name: Mend Unified CLI

on: workflow_dispatch

jobs:
  mend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
    - name: Mend SCA Scan
      env:
        MEND_EMAIL: ${{secrets.EMAIL}}
        MEND_USER_KEY: ${{secrets.USERKEY}}
        MEND_URL: https://saas.whitesourcesoftware.com
        MEND_PRODUCTNAME: ${{GITHUB_REPOSITORY_OWNER}}
        MEND_PROJECTNAME: ${{github.event.repository.name}}
      run: |
        sudo curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && sudo chmod +x /usr/local/bin/mend
        echo Mend CLI downloaded successfully
        echo ${{GITHUB_REPOSITORY_OWNER}}
        echo ${{github.event.repository.name}}
        mend sca -u -s "${{GITHUB_REPOSITORY_OWNER}}//${{github.event.repository.name}}"
    - name: 'Upload .mend/logs folder'
      uses: actions/upload-artifact@v2
      with:
        name: Mend logs
        path: /home/runner/.mend/logs/
        retention-days: 1
